### PR TITLE
Separate conditional testing for host and port as if host is not defined, then localhost is used by default

### PR DESCRIPTION
**Pull request by ehmo**

### CODE REVIEW

**Comment by ehmo** [comment]
I signed it!

**Comment by rimey** [comment]
Welcome, @ehmo! 

As I read the section on postgresql in the README, it says leaving `stackdriver_postgresql_host` undefined will cause the plugin to connect via a unix domain socket (in which case there would be no port), not `localhost`. If that is correct, the text could be clarified.

Could you please confirm what the plugin does when the `Host` clause is omitted in the configuration, and what `psql` does when the `--host` flag is omitted?

It might be helpful if you clarified whether you ran into a particular situation in which the existing code wasn't working for you. Cleanup is also fine, but we should be very careful not to break anything for other users.

**Comment by ehmo** [comment]
> As I read the section on postgresql in the README, it says leaving stackdriver_postgresql_host undefined will cause the plugin to connect via a unix domain socket (in which case there would be no port), not localhost. If that is correct, the text could be clarified.

You're correct that stackdriver itself will connect through the unix domain socket. However the diagnostic code in ansible is using psql and based on the [documentation](https://www.postgresql.org/docs/current/static/app-psql.html) 

>  If the value begins with a slash, it is used as the directory for the Unix-domain socket.

So this is pretty inconsistent. Anyway, I personally need to specify a port but I don't to run provide a host as I'm happy that `collectd` is using the socket while the `psql` is using directly the port. This is the easiest win-win.

I have this deployed in production already, but tested it out again to make sure everything work as it supposed to
`Aug 16 01:21:18 ubuntu collectd[24564]: Successfully connected to database text (user postgres) at server /var/run/postgresql/.s.PGSQL.5544 (server version: 9.5.4, protocol version: 3, pid: 24576)` 

`TASK [stackdriver : Test PostgreSQL connectivity] ******************************
ok: [*.*.*.*] => (item=test) => {"changed": false, "cmd": ["psql", "--username", "postgres", "--port", "5544", "--dbname", "test", "--command", "\\dt"], "delta": "0:00:00.071773", "end": "2016-08-16 01:21:22.858508", "item": "test", "rc": 0, "start": "2016-08-16 01:21:22.786735", "stderr": "", "stdout": "No relations found.", "stdout_lines": ["No relations found."], "warnings": []}`

So both the `collectd` and `psql` are working as supposed to.

**Comment by rimey** [comment]
That seems reasonable, but perhaps it would be clearer to leave `templates/postgresql.conf` unchanged? There's no need to include the port in the config when `stackdriver_postgresql_host` is undefined and the unix domain socket will be used.

Also, could you please fix the README to read something like the following: "When connecting to PostgreSQL, the plugin will connect using a unix domain socket."

**Comment by ehmo** [comment]
Sorry if I didn't make myself clear enough. The `collectd` will also fail as the socket does contain the port e.g. `/var/run/postgresql/.s.PGSQL.5544` so the template must be changed also.

I can add the information into the README however.

**Comment by rimey** [comment]
OK, I see. The code changes are good.

I would still suggest correcting the first sentence of the text to fix the spelling error and to use the standard term, "Unix domain socket". The sentence you proposed adding doesn't seem clear enough. I would suggest this instead: "When using a Unix domain socket, the port is incorporated into the path: `/var/run/postgresql/.s.PGSQL.5432`"

Please add line breaks to keep the formatting of the raw text consistent.

**Comment by rimey** [comment]
LGTM. It would have been nice to fix the small errors, but let's move on. Thank you for the contribution, and especially for testing it carefully. Merging...

**Pull request merged**
