### PR TITLE
add password option for redis plugin

### PR DESCRIPTION
**Pull request by csanquer**
Hi,

I added a new option for redis plugin to handle redis password (See [collectd doc](https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_redis)).

### CODE REVIEW

**Comment by rimey** [comment]
Hi,

I looked over the change but didn't test it. Could you confirm that you have tested it? Any useful details about your environment will be welcome, of course. Then I'll merge.

Cheers,

Ken

**Comment by csanquer** [comment]
Hi,

Sorry for the delay, but I can confirm it works : tested on 2 servers at work.
This PR fix the stackdriver redis plugin install process when the redis server is configured with a main password and clients need to use the [AUTH command ](http://redis.io/commands/AUTH) or the _-a_ option on redis-cli.

Cheers

Charles

**Comment by csanquer** [comment]
Tested with redis 3.0.7 on debian 8 jessie.

**Comment by rimey** [comment]
Thank you for this!

Ken

**Pull request merged**
